#!/bin/bash

REGISTRY=jptest01.mvista.com:5001
KOJIBASE_CONTAINER_NAME=koji-base-clear
KOJIBASE_CONTAINER_DOCKERFILE="Dockerfiles/koji-base-clear"

KOJI_CONTAINER_NAME=koji-docker
KOJI_CONTAINER_DOCKERFILE="Dockerfiles/koji-docker"

KOJIBUILDER_CONTAINER_NAME=koji-builder
KOJIBUILDER_CONTAINER_DOCKERFILE="Dockerfiles/builder"


CONTAINER_VERSIONS=$(date +%y%m%d)
CONTAINERS="$KOJIBASE_CONTAINER_NAME \
            $KOJI_CONTAINER_NAME \
	        $KOJIBUILDER_CONTAINER_NAME \
	        "

